Everthing is a box
onebeyond/css-pills pull request #15
Opened 2023-04-10 15:14 UTC by carpasse

Pill about CSS Box model

## Description
Added a pill about the Box model and about box-sizing property

## Related Issue
No issue, sorry. Shall I create one next time?

## Motivation and Context
The box model is one of the CORE concepts of CSS I wanted to add a pill giving a quick intro

2023-04-10 15:31 UTC, baumannzone requested changes
Very good pill! 
I let u a few comments. In addition, I would like to see an image maybe?

2023-04-11 15:53 UTC, carpasse commented on docs/pills/everything-is-a-box.md
> +  See the Pen <a href='https://codepen.io/carpasse/pen/LYJvPdY'>Box Model Example</a> by Your Name (<a href='https://codepen.io/carpasse'>@carpasse</a>) on <a href='https://codepen.io'>CodePen</a>.
because I copy pasted from an example in a blog post 🤦

2023-04-11 15:54 UTC, carpasse commented on docs/pills/everything-is-a-box.md
> +## Why border-box is Advised Instead of content-box
done

2023-04-11 15:55 UTC, carpasse commented on docs/pills/everything-is-a-box.md
> +tags: ['color', 'format']
Updated the tags to `layout` and `box model`.  Please let me know if you think I should use other tags.

2023-04-11 16:19 UTC, carpasse commented
@baumannzone With regards to the codepen, I've created a Vue component to embed codepens. Please let me know if that is ok or if you prefer to avoid the use of codepens.

2023-04-11 19:59 UTC, baumannzone commented on docs/pills/everything-is-a-box.md
> +tags: ['color', 'format']
I think those tags are ok, at the moment they are unused, but you never know

2023-04-12 17:08 UTC, carpasse commented
@baumannzone I've added a vue component to show the box model parts. I've left the codepen embed component just in case becomes useful later on. Please let me know if you wan't me to remove it.

2023-04-12 19:16 UTC, baumannzone commented
Hello! We discussed it and we don't want any embedded component here. Since you can create your own component here I suggest you to delete everything related to the old codepen component. 
I'll ping you tomorrow @carpasse 🤗

2023-04-13 14:57 UTC, baumannzone approved these changes

2023-04-13 14:58 UTC, merged

2023-04-15 10:46 UTC, baumannzone commented
please @all-contributors add @carpasse for blog